# Ruby&Railsをインストールしたイメージをベースに始める。
FROM rails_container:base

# 使用するシェルをbashに変更する
SHELL ["/bin/bash","-c"]

# アップデートをする。この文はDockerfile_baseと結合時に消す。
RUN apt-get update && apt-get upgrade -y
# nvmをダウンロードしてインストール
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash \
 && source ~/.bashrc

# node.jsをインストールする。
# yarnをインストール
RUN source ~/.nvm/nvm.sh \
 && nvm install 18.12.1 \ 
 && npm install --global yarn
 
# 作業ディレクトリを定義する
WORKDIR /home/rails_dir

# コンテナ起動時に/bin/bashを起動するように設定する。
CMD ["/bin/bash"]