FROM rails_container:tmp1

SHELL ["/bin/bash","-c"]
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv \
 && echo 'eval "$(~/.rbenv/bin/rbenv init - bash)"' >> ~/.bashrc \
 && source ~/.bashrc
ENV PATH="~/.rbenv/bin:$PATH"
RUN git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build \
 && rbenv install 3.1.2 \
 && rbenv global 3.1.2 \
 && rbenv rehash