FROM ubuntu:22.04
RUN apt-get update && apt-get upgrade -y
RUN apt-get install git autoconf bison patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev curl sqlite3 libsqlite3-dev -y
